/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lusniam.grupa2;

import java.io.FileWriter;
import java.util.Random;
import java.io.File;
import java.io.IOException;
import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author Maciej
 */
class PainterThread implements Runnable{
    int counter = 0;
    Random rand = new Random();
    JPanel Canva;
    FileWriter fw;
    int nrWatku;
    
    PainterThread(){
        Canva=new JPanel();
    }
    
    PainterThread(JPanel c, FileWriter f,int i){
        Canva=c;
        fw=f;
        nrWatku=i;
    }
    
    @Override
    public void run(){
        while(counter<3){
            try{
                paint();
                counter++;
            }
            catch(InterruptedException | IOException ex){
                Logger.getLogger(Grupa2UI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    private void paint() throws InterruptedException, IOException{
            int x=rand.nextInt(600);
            int y=rand.nextInt(400);
            int r=rand.nextInt(100);
            Canva.getGraphics().fillOval(x,y,r,r);
            fw.append(Thread.currentThread().getName());
            fw.append("Nr watku: "+Integer.toString(nrWatku)+", x: "+Integer.toString(x)+", y: "+Integer.toString(y)+", r: "+Integer.toString(r)+"\n");
            Thread.sleep(1000);
        
    }
}

public class Grupa2UI extends javax.swing.JFrame{
    File file;
    FileWriter fw;
    
    /**
     * Creates new form Grupa2UI
     */
    public Grupa2UI() {
        this.file = new File("okregi.txt");
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RysujButton = new javax.swing.JButton();
        Canva = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 434));
        setMinimumSize(new java.awt.Dimension(600, 434));

        RysujButton.setLabel("Rysuj");
        RysujButton.setMaximumSize(new java.awt.Dimension(1800, 600));
        RysujButton.setMinimumSize(new java.awt.Dimension(60, 20));
        RysujButton.setPreferredSize(new java.awt.Dimension(60, 20));
        RysujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RysujButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CanvaLayout = new javax.swing.GroupLayout(Canva);
        Canva.setLayout(CanvaLayout);
        CanvaLayout.setHorizontalGroup(
            CanvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        CanvaLayout.setVerticalGroup(
            CanvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(RysujButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(Canva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Canva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RysujButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void RysujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RysujButtonActionPerformed
        Random rand = new Random();
        try {
            this.fw = new FileWriter(file);
            Thread[] t = new Thread[5];
            for(int i=0;i<5;i++){
                t[i] = new Thread(new PainterThread(Canva,fw,i));
            }
            int n = rand.nextInt(1,5);
            for(int i=0;i<n;i++){
                t[i].run();
            }
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(Grupa2UI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RysujButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grupa2UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grupa2UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grupa2UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grupa2UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grupa2UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Canva;
    private javax.swing.JButton RysujButton;
    // End of variables declaration//GEN-END:variables
}
