/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lusniam.kalkulator;

/**
 *
 * @author Maciej
 */
public class KalkulatorUI extends javax.swing.JFrame {
    private char znak='0';
    private double number;
    private boolean isNewNumber=false;
    /**
     * Creates new form NewJFrame
     */
    public KalkulatorUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Button2 = new javax.swing.JButton();
        Button3 = new javax.swing.JButton();
        Button4 = new javax.swing.JButton();
        Button5 = new javax.swing.JButton();
        Button6 = new javax.swing.JButton();
        Button7 = new javax.swing.JButton();
        Button8 = new javax.swing.JButton();
        Button9 = new javax.swing.JButton();
        Button0 = new javax.swing.JButton();
        ButtonDot = new javax.swing.JButton();
        ButtonEqual = new javax.swing.JButton();
        ButtonPlus = new javax.swing.JButton();
        ButtonMinus = new javax.swing.JButton();
        ButtonMul = new javax.swing.JButton();
        ButtonDiv = new javax.swing.JButton();
        ButtonPow = new javax.swing.JButton();
        ButtonClear = new javax.swing.JButton();
        ButtonSqrt = new javax.swing.JButton();
        Button1 = new javax.swing.JButton();
        TextLabel = new javax.swing.JLabel();
        ButtonDeg = new javax.swing.JButton();
        ButtonRad = new javax.swing.JButton();
        ButtonBin = new javax.swing.JButton();
        ButtonDec = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulator");
        setPreferredSize(new java.awt.Dimension(359, 420));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        Button2.setText("2");
        Button2.setMaximumSize(new java.awt.Dimension(200, 200));
        Button2.setMinimumSize(new java.awt.Dimension(30, 30));
        Button2.setPreferredSize(new java.awt.Dimension(60, 30));
        Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(Button2, gridBagConstraints);

        Button3.setText("3");
        Button3.setMaximumSize(new java.awt.Dimension(200, 200));
        Button3.setMinimumSize(new java.awt.Dimension(30, 30));
        Button3.setPreferredSize(new java.awt.Dimension(60, 30));
        Button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(Button3, gridBagConstraints);

        Button4.setText("4");
        Button4.setMaximumSize(new java.awt.Dimension(200, 200));
        Button4.setMinimumSize(new java.awt.Dimension(40, 40));
        Button4.setPreferredSize(new java.awt.Dimension(60, 30));
        Button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(Button4, gridBagConstraints);

        Button5.setText("5");
        Button5.setMaximumSize(new java.awt.Dimension(200, 200));
        Button5.setMinimumSize(new java.awt.Dimension(30, 30));
        Button5.setPreferredSize(new java.awt.Dimension(60, 30));
        Button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(Button5, gridBagConstraints);

        Button6.setText("6");
        Button6.setMaximumSize(new java.awt.Dimension(200, 200));
        Button6.setMinimumSize(new java.awt.Dimension(30, 30));
        Button6.setPreferredSize(new java.awt.Dimension(60, 30));
        Button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(Button6, gridBagConstraints);

        Button7.setText("7");
        Button7.setMaximumSize(new java.awt.Dimension(200, 200));
        Button7.setMinimumSize(new java.awt.Dimension(30, 30));
        Button7.setPreferredSize(new java.awt.Dimension(60, 30));
        Button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(Button7, gridBagConstraints);

        Button8.setText("8");
        Button8.setMaximumSize(new java.awt.Dimension(200, 200));
        Button8.setMinimumSize(new java.awt.Dimension(30, 30));
        Button8.setPreferredSize(new java.awt.Dimension(60, 30));
        Button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(Button8, gridBagConstraints);

        Button9.setText("9");
        Button9.setMaximumSize(new java.awt.Dimension(200, 200));
        Button9.setMinimumSize(new java.awt.Dimension(30, 30));
        Button9.setPreferredSize(new java.awt.Dimension(60, 30));
        Button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(Button9, gridBagConstraints);

        Button0.setText("0");
        Button0.setMaximumSize(new java.awt.Dimension(200, 200));
        Button0.setMinimumSize(new java.awt.Dimension(30, 30));
        Button0.setPreferredSize(new java.awt.Dimension(70, 30));
        Button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button0ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 70;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(Button0, gridBagConstraints);

        ButtonDot.setText(".");
        ButtonDot.setMaximumSize(new java.awt.Dimension(200, 200));
        ButtonDot.setMinimumSize(new java.awt.Dimension(30, 30));
        ButtonDot.setPreferredSize(new java.awt.Dimension(60, 30));
        ButtonDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDotActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(ButtonDot, gridBagConstraints);

        ButtonEqual.setText("=");
        ButtonEqual.setMaximumSize(new java.awt.Dimension(200, 200));
        ButtonEqual.setMinimumSize(new java.awt.Dimension(30, 30));
        ButtonEqual.setPreferredSize(new java.awt.Dimension(60, 30));
        ButtonEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEqualActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(ButtonEqual, gridBagConstraints);

        ButtonPlus.setText("+");
        ButtonPlus.setMaximumSize(new java.awt.Dimension(200, 200));
        ButtonPlus.setMinimumSize(new java.awt.Dimension(30, 30));
        ButtonPlus.setPreferredSize(new java.awt.Dimension(60, 30));
        ButtonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPlusActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(ButtonPlus, gridBagConstraints);

        ButtonMinus.setText("-");
        ButtonMinus.setMaximumSize(new java.awt.Dimension(200, 200));
        ButtonMinus.setMinimumSize(new java.awt.Dimension(30, 30));
        ButtonMinus.setPreferredSize(new java.awt.Dimension(60, 30));
        ButtonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMinusActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(ButtonMinus, gridBagConstraints);

        ButtonMul.setText("*");
        ButtonMul.setMaximumSize(new java.awt.Dimension(200, 200));
        ButtonMul.setMinimumSize(new java.awt.Dimension(30, 30));
        ButtonMul.setPreferredSize(new java.awt.Dimension(60, 30));
        ButtonMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMulActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(ButtonMul, gridBagConstraints);

        ButtonDiv.setText("/");
        ButtonDiv.setMaximumSize(new java.awt.Dimension(200, 200));
        ButtonDiv.setMinimumSize(new java.awt.Dimension(30, 30));
        ButtonDiv.setPreferredSize(new java.awt.Dimension(60, 30));
        ButtonDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDivActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(ButtonDiv, gridBagConstraints);

        ButtonPow.setText("^");
        ButtonPow.setMaximumSize(new java.awt.Dimension(200, 200));
        ButtonPow.setMinimumSize(new java.awt.Dimension(30, 30));
        ButtonPow.setPreferredSize(new java.awt.Dimension(60, 30));
        ButtonPow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPowActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(ButtonPow, gridBagConstraints);

        ButtonClear.setText("C");
        ButtonClear.setMaximumSize(new java.awt.Dimension(200, 200));
        ButtonClear.setMinimumSize(new java.awt.Dimension(30, 30));
        ButtonClear.setPreferredSize(new java.awt.Dimension(60, 30));
        ButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClearActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(ButtonClear, gridBagConstraints);

        ButtonSqrt.setText("SQT");
        ButtonSqrt.setMaximumSize(new java.awt.Dimension(200, 200));
        ButtonSqrt.setMinimumSize(new java.awt.Dimension(30, 30));
        ButtonSqrt.setPreferredSize(new java.awt.Dimension(60, 30));
        ButtonSqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSqrtActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(ButtonSqrt, gridBagConstraints);

        Button1.setText("1");
        Button1.setMaximumSize(new java.awt.Dimension(200, 200));
        Button1.setMinimumSize(new java.awt.Dimension(30, 30));
        Button1.setPreferredSize(new java.awt.Dimension(60, 30));
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(Button1, gridBagConstraints);

        TextLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TextLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TextLabel.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(TextLabel, gridBagConstraints);

        ButtonDeg.setText("DEG");
        ButtonDeg.setMaximumSize(new java.awt.Dimension(200, 200));
        ButtonDeg.setMinimumSize(new java.awt.Dimension(30, 30));
        ButtonDeg.setPreferredSize(new java.awt.Dimension(60, 30));
        ButtonDeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDegActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(ButtonDeg, gridBagConstraints);

        ButtonRad.setText("RAD");
        ButtonRad.setMaximumSize(new java.awt.Dimension(200, 200));
        ButtonRad.setMinimumSize(new java.awt.Dimension(30, 30));
        ButtonRad.setPreferredSize(new java.awt.Dimension(60, 30));
        ButtonRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRadActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(ButtonRad, gridBagConstraints);

        ButtonBin.setText("BIN");
        ButtonBin.setMaximumSize(new java.awt.Dimension(200, 200));
        ButtonBin.setMinimumSize(new java.awt.Dimension(30, 30));
        ButtonBin.setPreferredSize(new java.awt.Dimension(60, 30));
        ButtonBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBinActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(ButtonBin, gridBagConstraints);

        ButtonDec.setText("DEC");
        ButtonDec.setMaximumSize(new java.awt.Dimension(200, 200));
        ButtonDec.setMinimumSize(new java.awt.Dimension(30, 30));
        ButtonDec.setPreferredSize(new java.awt.Dimension(60, 30));
        ButtonDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDecActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(ButtonDec, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChangeNum(int num){
        if (num==0&&TextLabel.getText().equals("0")){
            return;
        }
        else if(TextLabel.getText().equals("0")){
            TextLabel.setText(Integer.toString(num));
        }
        else if(isNewNumber){
            TextLabel.setText(Integer.toString(num));
            isNewNumber=false;
        }
        else{
            TextLabel.setText(TextLabel.getText()+Integer.toString(num));
        }
    }
    
    private void HandleFunc(char zn){
        if(znak!='0'&&isNewNumber==false){
            this.ButtonEqual.doClick();
        }
        number=Double.parseDouble(TextLabel.getText());
        znak=zn;
        isNewNumber=true;
    }

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        ChangeNum(1);
    }//GEN-LAST:event_Button1ActionPerformed

    private void Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button3ActionPerformed
        ChangeNum(3);
    }//GEN-LAST:event_Button3ActionPerformed

    private void Button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button4ActionPerformed
        ChangeNum(4);
    }//GEN-LAST:event_Button4ActionPerformed

    private void Button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button6ActionPerformed
        ChangeNum(6);
    }//GEN-LAST:event_Button6ActionPerformed

    private void Button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button7ActionPerformed
        ChangeNum(7);
    }//GEN-LAST:event_Button7ActionPerformed

    private void Button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button9ActionPerformed
        ChangeNum(9);
    }//GEN-LAST:event_Button9ActionPerformed

    private void Button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button0ActionPerformed
        ChangeNum(0);
    }//GEN-LAST:event_Button0ActionPerformed

    private void ButtonDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDotActionPerformed
        if(TextLabel.getText().lastIndexOf(".")==-1){
            TextLabel.setText(TextLabel.getText()+".");
        }
    }//GEN-LAST:event_ButtonDotActionPerformed

    private void ButtonEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEqualActionPerformed
        double result;
        switch(znak){
            case '+':{
                result = number + Double.parseDouble(TextLabel.getText());
                break;
            }
            case '-':{
                result = number - Double.parseDouble(TextLabel.getText());
                break;
            }
            case '*':{
                result = number * Double.parseDouble(TextLabel.getText());
                break;
            }
            case '/':{
                result = number / Double.parseDouble(TextLabel.getText());
                break;
            }
            case '^':{
                result = Math.pow(number,Double.parseDouble(TextLabel.getText()));
                break;
            }
            default:
                return;
        }
        znak='0';
        TextLabel.setText(result%1.0!=0 ? String.format("%s", result) : String.format("%.0f", result));
    }//GEN-LAST:event_ButtonEqualActionPerformed

    private void ButtonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPlusActionPerformed
        HandleFunc('+');
    }//GEN-LAST:event_ButtonPlusActionPerformed

    private void ButtonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMinusActionPerformed
        HandleFunc('-');
    }//GEN-LAST:event_ButtonMinusActionPerformed

    private void ButtonMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMulActionPerformed
        HandleFunc('*');
    }//GEN-LAST:event_ButtonMulActionPerformed

    private void ButtonDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDivActionPerformed
        HandleFunc('/');
    }//GEN-LAST:event_ButtonDivActionPerformed

    private void ButtonPowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPowActionPerformed
        HandleFunc('^');
    }//GEN-LAST:event_ButtonPowActionPerformed

    private void ButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonClearActionPerformed
        TextLabel.setText("0");
    }//GEN-LAST:event_ButtonClearActionPerformed

    private void ButtonSqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSqrtActionPerformed
        double result=Math.sqrt(Double.parseDouble(TextLabel.getText()));
        TextLabel.setText(result%1.0!=0 ? String.format("%s", result) : String.format("%.0f", result));
    }//GEN-LAST:event_ButtonSqrtActionPerformed

    private void ButtonDegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDegActionPerformed
        double result=Double.parseDouble(TextLabel.getText())*180;
        TextLabel.setText(result%1.0!=0 ? String.format("%s", result) : String.format("%.0f", result));
    }//GEN-LAST:event_ButtonDegActionPerformed

    private void ButtonRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRadActionPerformed
        double result=Double.parseDouble(TextLabel.getText())/180;
        TextLabel.setText(result%1.0!=0 ? String.format("%s", result) : String.format("%.0f", result));
    }//GEN-LAST:event_ButtonRadActionPerformed

    private void ButtonBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBinActionPerformed
        TextLabel.setText(Integer.toBinaryString(Integer.parseInt(TextLabel.getText())));
    }//GEN-LAST:event_ButtonBinActionPerformed

    private void ButtonDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDecActionPerformed
        TextLabel.setText(Integer.toString(Integer.parseInt(TextLabel.getText(),2)));
    }//GEN-LAST:event_ButtonDecActionPerformed

    private void Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2ActionPerformed
        ChangeNum(2);
    }//GEN-LAST:event_Button2ActionPerformed

    private void Button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button5ActionPerformed
        ChangeNum(5);
    }//GEN-LAST:event_Button5ActionPerformed

    private void Button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button8ActionPerformed
        ChangeNum(8);
    }//GEN-LAST:event_Button8ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KalkulatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KalkulatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KalkulatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KalkulatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KalkulatorUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button0;
    private javax.swing.JButton Button1;
    private javax.swing.JButton Button2;
    private javax.swing.JButton Button3;
    private javax.swing.JButton Button4;
    private javax.swing.JButton Button5;
    private javax.swing.JButton Button6;
    private javax.swing.JButton Button7;
    private javax.swing.JButton Button8;
    private javax.swing.JButton Button9;
    private javax.swing.JButton ButtonBin;
    private javax.swing.JButton ButtonClear;
    private javax.swing.JButton ButtonDec;
    private javax.swing.JButton ButtonDeg;
    private javax.swing.JButton ButtonDiv;
    private javax.swing.JButton ButtonDot;
    private javax.swing.JButton ButtonEqual;
    private javax.swing.JButton ButtonMinus;
    private javax.swing.JButton ButtonMul;
    private javax.swing.JButton ButtonPlus;
    private javax.swing.JButton ButtonPow;
    private javax.swing.JButton ButtonRad;
    private javax.swing.JButton ButtonSqrt;
    private javax.swing.JLabel TextLabel;
    // End of variables declaration//GEN-END:variables
}
